### PR TITLE
Feature splash and about page styling

### PR DESCRIPTION
**Pull request by curtisahuang**
## Description

Changing the splash and about pages to have more consistent styling and look

## Screenshots

newniwa
Option 1
newabout
Option 2
newabout2

## Changes include

- [X] New feature (non-breaking change that adds functionality)

## Checklist

- [ ] I have tested this code

### CODE REVIEW

**Comment by curtisahuang** [comment]
Two designs so far for the about page. Any thoughts?

**Comment by daiHash** [comment]
Both design looks good. 
What about using pixel art for the image to match with the current theme of the app? 
garden

**Comment by curtisahuang** [comment]
Yeah, pixel art fits with the theme better.  Let me see if I can find a nice "niwa" pixel art

**Comment by curtisahuang** [comment]
newabout3

**Review by daiHash — APPROVED** [review]
Nice LGTM!👍

**Review by kome12 — APPROVED** [review]
LGTM!

**Review by conalli — APPROVED** [review]
lgtm!

**Pull request merged**
